allauthdemo/polls/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'polls'

#urlpatterns = [
#  url(r'^$', views.index, name='index'),
  # ex: /polls/5/
#  url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
  # ex: /polls/5/results/
#  url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
  # ex: /polls/5/vote/
#  url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
#]

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', login_required(views.vote), name='vote'),
]

allauthdemo/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'polls'

#urlpatterns = [
#  url(r'^$', views.index, name='index'),
  # ex: /polls/5/
#  url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
  # ex: /polls/5/results/
#  url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
  # ex: /polls/5/vote/
#  url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
#]

urlpatterns = [
    url(r'^vote/(?P<poll_id>[0-9]+)/$', views.test_poll_vote, name='vote-poll'),
    url(r'^(?P<pk>[0-9]+)/$', views.EventDetailView.as_view(), name='view-event'),
    url(r'^(?P<pk>[0-9]+)/polls$', views.EventDetailPollsView.as_view(), name='event-polls'),
    url(r'^(?P<pk>[0-9]+)/organisers$', views.EventDetailOrganisersView.as_view(), name='event-organisers'),
    url(r'^$', views.EventListView.as_view(), name='index'),
    url(r'^create/$', login_required(views.create_event), name='create-event'),
    url(r'^(?P<event_id>[0-9]+)/decrypt/$', login_required(views.event_trustee_decrypt), name='decrypt-event'),
    url(r'^(?P<event_id>[0-9]+)/prepare/$', login_required(views.event_trustee_setup), name='prepare-event'),
    url(r'^(?P<event_id>[0-9]+)/encrypt/$', login_required(views.event_addec), name='enc-event'),
    url(r'^(?P<pk>[0-9]+)/launch/$', views.EventDetailLaunchView.as_view(), name='launch-event'),
    url(r'^edit/(?P<event_id>[0-9]+)/$', login_required(views.edit_event), name='edit-event'),
    url(r'^(?P<event_id>[0-9]+)/create/poll/$', login_required(views.manage_questions), name='create-poll'),
    url(r'^(?P<event_id>[0-9]+)/poll/(?P<poll_num>[0-9]+)/$', login_required(views.view_poll), name='view-poll'),
    url(r'^(?P<event_id>[0-9]+)/poll/(?P<poll_num>[0-9]+)/edit$', login_required(views.edit_poll), name='edit-poll'),
    #url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    #url(r'^(?P<pk>[0-9]+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', login_required(views.vote), name='vote'),
]

allauthdemo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

import allauthdemo.views
import allauthdemo.auth.views
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='visitor/landing-index.html'), name='landing_index'),
    url(r'^about$', TemplateView.as_view(template_name='visitor/landing-about.html'), name='landing_about'),
    url(r'^terms/$', TemplateView.as_view(template_name='visitor/terms.html'), name='website_terms'),
    url(r'^contact$', TemplateView.as_view(template_name='visitor/contact.html'), name='website_contact'),

    url(r'^event/', include('allauthdemo.polls.urls', namespace="polls")),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', allauthdemo.auth.views.account_profile, name='account_profile'),

    url(r'^member/$', allauthdemo.views.member_index, name='user_home'),
    url(r'^member/events$', allauthdemo.views.MemberEvents.as_view(), name='account_events'),
    url(r'^member/action$', allauthdemo.views.member_action, name='user_action'),

    url(r'^admin/', include(admin.site.urls))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

allauthdemo/demo/models.py
from django.db import models

# Create your models here.

allauthdemo/polls/models.py
from __future__ import unicode_literals

from django.db import models

from django import forms

# Create your models here.

import datetime

from django.utils import timezone

from allauthdemo.auth.models import DemoUser

class EmailUser(models.Model):
    email = models.CharField(max_length=80, unique=True)

class Event(models.Model):
    users_organisers = models.ManyToManyField(DemoUser, blank=True, related_name="organisers")
    users_trustees = models.ManyToManyField(EmailUser, blank=True, related_name="trustees")
    voters = models.ManyToManyField(EmailUser, blank=True, related_name="voters")
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    prepared = models.BooleanField(default=False)
    public_key = models.CharField(null=True, blank=False, max_length=1024)
    title = models.CharField(max_length=1024)
    EID = models.CharField(max_length=512, blank=True)
    creator = models.CharField(max_length=256, blank=True)
    c_email = models.CharField(max_length=512, blank=True)
    trustees = models.CharField(max_length=4096)

class TrusteeKey(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="trustee_keys")
    user = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="trustee_keys")
    key = models.CharField(max_length=1024, unique=True) # ideally composite key here, but django doesn't really support yet

class AccessKey(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="keys")
    user = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="keys")
    key = models.CharField(max_length=1024, unique=True) # ideally composite key here, but django doesn't really support yet

    #total = models.IntegerField(blank=True, null=True, default=0)

    def has_started(self):
        return timezone.now() >= self.start

    def has_ended(self):
        return timezone.now() >= self.end

    def __unicode__(self):
        return self.title

class Poll(models.Model):
    question_text = models.CharField(max_length=200)
    total_votes = models.IntegerField(default=0)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="polls")
    enc = models.CharField(max_length=4096, null=True)

    #index = models.IntegerField()

    def __str__(self):
        return self.question_text

class Decryption(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="decryptions")
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="decryptions")
    user = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="decryptions")
    text = models.CharField(max_length=1024)

class Ballot(models.Model):
    voter = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="ballots")
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="ballots")
    cipher_text = models.CharField(max_length=4096)
    cast = models.BooleanField(default=False)

class PollOption(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="options")
    #index = models.IntegerField()

class Organiser(models.Model):
    index = models.IntegerField(default=0)
    email = models.CharField(max_length=100, blank=False, null=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

'''
class Organiser(models.Model):
    user = models.ForeignKey(DemoUser, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

class Trustee(models.Model):
    user = models.ForeignKey(DemoUser, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    '''
#class EventOrganisers():
    #event = models.ForeignKey(Event, on_delete=models.CASCADE)

allauthdemo/polls/polls/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

import datetime

from django.utils import timezone

class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')

  def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

  was_published_recently.admin_order_field = 'pub_date'
  was_published_recently.boolean = True
  was_published_recently.short_description = 'Published recently?'

  def __str__(self):
    return self.question_text

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

  def __str__(self):
    return self.choice_text

allauthdemo/demo/views.py
from django.shortcuts import render

# Create your views here.

allauthdemo/polls/polls/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render

from django.utils import timezone

from .models import Question, Choice

from django.views import generic


""" from allauthdemo.auth.forms import RegistrationForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegistrationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegistrationForm()

    return render(request, 'polls/index.html', {'form': form}) """


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
# ...
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

allauthdemo/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from allauthdemo.polls.models import Event
from django.shortcuts import get_object_or_404, render, render_to_response

@login_required
def member_index(request):
    return render_to_response("member/member-index.html", RequestContext(request))


#def member_events(request):
    #self.publisher = get_object_or_404(Publisher, name=self.args[0])
    #return Book.objects.filter(publisher=self.publisher)
    #return render_to_response("member/member-events.html", RequestContext(request))

class MemberEvents(generic.ListView):
    model = Event
    template_name = 'member/member-events.html'

    def get_context_data(self, **kwargs):
        context = super(MemberEvents, self).get_context_data(**kwargs)
        #self.object.organisers.filter(email=self.request.user.email())
        # no check needed for anon, as url should make sure we're logged in!
        return context

    def get_queryset(self):
        #self.publisher = get_object_or_404(Publisher, name=self.args[0])
        return self.request.user.organisers.all()

@login_required
def member_action(request):
    return render_to_response("member/member-action.html", RequestContext(request))




'''

class EventListView(generic.ListView):

    model = Event

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        #context['now'] = timezone.now()
        return context

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        context['is_organiser'] = ((not self.request.user.is_anonymous()) and (self.object.users.filter(email=self.request.user.email).exists()))
        #context['now'] = timezone.now()
        return context

class PollDetailView(generic.DetailView):

    model = Poll

    def get_context_data(self, **kwargs):
        context = super(PollDetailView, self).get_context_data(**kwargs)
        #context['now'] = timezone.now()
        context['form'] = VoteForm(instance=self.object)
        context['poll_count'] = self.object.event.polls.all().count()
        return context

'''

allauthdemo/templates/polls/create_event.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
 <h1>Create Event</h1>
 {% load crispy_forms_tags %}
 <form method="post" action="" enctype="multipart/form-data" class="">
    {% comment %}
      enctype necessary for file uploads
    {% endcomment %}
    {% crispy form %}
    <input class="btn btn-default" type="submit" value="Submit"/>
</form>
</div>

{% endblock %}

allauthdemo/templates/polls/create_option.html
{% load crispy_forms_tags %}

<div class="formset">
    {% crispy formset helper %}
    <button type="button" class="btn btn-default add-another-btn" name="add" value="Add another">Add</button>
</div>

allauthdemo/templates/polls/create_poll.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
 <h1>Create Poll for {{event.title}}</h1>
 {% load crispy_forms_tags %}
 <form method="post" action="" class="">
    {% crispy question_form %}
    <input class="btn btn-default" type="submit" value="Submit"/>
</form>
</div>


{% endblock %}

allauthdemo/templates/polls/detail.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}

{% block content %}

<div class="container">
 <h1>{{ question.question_text }}</h1>

 {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

 <form action="{% url 'polls:vote' question.id %}" method="post">
   {% csrf_token %}
   {% for choice in question.choice_set.all %}
     <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
     <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
   {% endfor %}
   <input type="submit" value="Vote" />
 </form>
</div>

{% endblock %}

allauthdemo/templates/polls/event_decrypt.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% comment %} is it safe really? {% endcomment %}
{% block sk-file-name %}{{ event.title|safe }}{% endblock %}

{% block content %}

<div class="container">
  <h1>Event: {{event.title}}</h1>
  <h2>Trustee Decrypt</h2>
  <div class="panel panel-default">
    <div class="panel-heading">Secret Key</div>
    <div class="panel panel-body">
      <input id="secret-key" class="textinput textInput form-control" type="text"></input>
      <p>Use your secret key to generate a decrypted cipher</p>
      <button id="keygen-btn" onclick="demosEncrypt.decryptCipher()" class="btn btn-default">Decrypt</button>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">Encrypted Ciphers</div>
    <div class="panel panel-body">
      {% load crispy_forms_tags %}
      <form method="post" action="" class="">
         {% crispy formset helper %}
         <input class="btn btn-default" type="submit" value="Submit" disabled>
     </form>
    </div>
  </div>
</div>

{% endblock %}

allauthdemo/templates/polls/event_detail_details.html
{% extends "polls/event_detail_base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block event_nav_details %}active{% endblock %}
{% block event_content %}
<h2>Event Details</h2>
  <span>Ready/Prepared: {{ event.prepared }}</span>
  <br />
  <span>Start Time: {{ event.start_time }}</span>
  <br />
  <span>End Time: {{ event.end_time }}</span>
{% endblock %}

allauthdemo/templates/polls/event_detail_organisers.html
{% extends "polls/event_detail_base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block event_nav_organisers %}active{% endblock %}
{% block event_content %}
<h2>Event Organisers</h2>
  {% if object.users_organisers.all %}
    <ul class="list-group">
      {% for user in object.users_organisers.all %}
      <li class="list-group-item">{{ user.email }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No Organisers for this Event.</p>
  {% endif %}
  <h2>Event Trustees</h2>
  {% if object.users_trustees.all %}
    <ul class="list-group">
      {% for user in object.users_trustees.all %}
      <li class="list-group-item">{{ user.email }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No Organisers for this Event.</p>
  {% endif %}
  <h2>Voters</h2>
  {% if object.voters.all %}
    <ul class="list-group">
      {% for voter in object.voters.all %}
      <li class="list-group-item">{{ voter.email }}</li>
      {% endfor %}
    </ul>
    {% else %}
      <p>No voters for this Event.</p>
    {% endif %}
{% endblock %}

allauthdemo/templates/polls/event_list.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}

{% block content %}

 <div class="container">
   <h1>Events</h1>
   <div class="btn-group panel" role="group" aria-label="...">
     <a href="{% url 'polls:create-event' %}" class="btn btn-default" role="button">Create Event</a>
   </div>
   {% if object_list %}
     <ul class="list-group">
       {% for event in object_list %}
         <li class="list-group-item"><a href="{% url 'polls:view-event' event.id %}">{{ event.title }}</a> - {{ event.start_time }}</li>
       {% endfor %}
     </ul>
   {% else %}
     <p>No Events are available.</p>
   {% endif %}
 </div>

{% endblock %}

allauthdemo/templates/polls/event_setup.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% comment %} is it safe really? {% endcomment %}
{% block sk-file-name %}{{ event.title|safe }}{% endblock %}

{% block content %}

<div class="container">
  <h1>Event: {{event.title}}</h1>
  <h2>Trustee Setup</h2>
  <div class="panel panel-default">
    <div class="panel-heading">Public Key</div>
    <div class="panel panel-body">
      {% load crispy_forms_tags %}
      <form method="post" action="" class="">
         {% crispy form %}
         <input class="btn btn-default" type="submit" value="Submit"/>
     </form>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">Secret Key</div>
    <div class="panel panel-body">
      <input id="secret-key" class="textinput textInput form-control" type="text"></input>
      <input id="event-param" type="text" value="{{event.EID}}" hidden></input>
      <p>Make a backup of this secret key before submitting your public key. This can NOT be recalculated if forgotten!</p>
      <button id="keygen-btn" onclick="demosEncrypt.generateKeys()" class="btn btn-default">Generate</button>
      <a id="download-btn" role="button" href="#" class="btn btn-default" disabled>Download</a>
    </div>
  </div>
</div>

{% endblock %}

allauthdemo/templates/polls/generic_form.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
  <h1>{{ form_title }}</h1>
  {% load crispy_forms_tags %}
  <form method="post" action="" {{ form_attributes }} class="">
    {% crispy form %}
    <input class="btn btn-default" type="submit" value="Submit"/>
  </form>
</div>

{% endblock %}

allauthdemo/templates/polls/poll_detail.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block app_js_vars %}
  var param = "{{ event.EID }}";
  var comb_pk = "{{ event.public_key }}";
  var option_count = {{ object.options.count }};
{% endblock %}

{% block content %}

<div class="container">
 <h1>Poll: {{object.question_text}}</h1>
 <span>Poll {{ poll_num }} of {{ poll_count }} in Event: <a href="{% url 'polls:view-event' object.event.id %}">{{ object.event.title }}</a></span>
 <div class="panel panel-body">
  {% if prev_index %}
    <a href="{% url 'polls:view-poll' event_id=object.event.id poll_num=prev_index %}" class="btn" role="button">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </a>
  {% endif %}
  {% if next_index %}
  <a href="{% url 'polls:view-poll' event_id=object.event.id poll_num=next_index %}" class="btn" role="button">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
  </a>
  {% endif %}
 </div>
 <a href="{% url 'polls:edit-poll' event_id=object.event.id poll_num=poll_num %}"><span class="fa fa-pencil"></span> Edit Poll</a>
 {% if object.options.all %}
   <h3>Options</h3>
   <p> {{ vote_count }} vote(s) have been cast</p>
   {% if can_vote %}
     {% if has_voted %}
       <p>You have already voted in this poll. Resubmitting the form will change your vote.</p>
     {% endif %}
     <p>Voting as {{ voter_email }} -- Do NOT share this url</p>
     {% load crispy_forms_tags %}
     <div class="panel panel-default">
       <div class="panel-heading">Options</div>
       <div class="panel panel-body">
         <select class="radio-inline select form-control" id="poll-options" name="options">
           {% for option in object.options.all %}
             <option value="{{forloop.counter}}">{{ option.choice_text }}</option>
           {% endfor %}
         </select>
         <p>Make a backup of this secret key before submitting your public key. This can NOT be recalculated if forgotten!</p>
         <button id="keygen-btn" onclick="demosEncrypt.encryptAndSubmit()" class="btn btn-default">Encrypt & Submit</button>
         <form id="cipher-form" method="post" action="" class="">
             {% crispy form %}
          {% csrf_token %}
         </form>
       </div>
     </div>
   {% else %}
     <div class="alert alert-warning" role="alert">
       <p>You do not have permission to vote in this Event.</p>
     </div>
   {% endif %}
 {% else %}
   <p>No options are available.</p>
 {% endif %}
</div>
<br>
<br>
POLL ENC {{ object.enc }}

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}

allauthdemo/templates/polls/results.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}

{% block content %}

 <div class="container">

    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li class="list-group-item">{{ choice.choice_text }} <span class="badge">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span></li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>

</div>

{% endblock %}

allauthdemo/templates/polls/view_poll_detail.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
 <h1>Poll: {{poll.question_text}}</h1>
 {% if poll.options %}
   <ul class="list-group">
     {% for option in poll.options.all %}
       <li class="list-group-item">{{ option.choice_text }}</li>
     {% endfor %}
   </ul>
 {% else %}
   <p>No options are listed.</p>
 {% endif %}
</div>


{% endblock %}

allauthdemo/templates/polls/vote_poll.html
{% extends "bases/bootstrap-with-nav.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
 <h1>Vote on {{poll.question_text}}</h1>
 {% load crispy_forms_tags %}
 <form method="post" action="" class="">
    {% crispy vote_form %}
    <input class="btn btn-default" type="submit" value="Submit"/>
</form>
</div>


{% endblock %}