allauthdemo/polls/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'polls'

#urlpatterns = [
#  url(r'^$', views.index, name='index'),
  # ex: /polls/5/
#  url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
  # ex: /polls/5/results/
#  url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
  # ex: /polls/5/vote/
#  url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
#]

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', login_required(views.vote), name='vote'),
]

allauthdemo/polls/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'polls'

#urlpatterns = [
#  url(r'^$', views.index, name='index'),
  # ex: /polls/5/
#  url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
  # ex: /polls/5/results/
#  url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
  # ex: /polls/5/vote/
#  url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
#]

urlpatterns = [
    url(r'^vote/(?P<poll_id>[0-9]+)/$', views.test_poll_vote, name='vote-poll'),
    url(r'^(?P<pk>[0-9]+)/$', views.EventDetailView.as_view(), name='view-event'),
    url(r'^(?P<pk>[0-9]+)/polls$', views.EventDetailPollsView.as_view(), name='event-polls'),
    url(r'^(?P<pk>[0-9]+)/organisers$', views.EventDetailOrganisersView.as_view(), name='event-organisers'),
    url(r'^$', views.EventListView.as_view(), name='index'),
    url(r'^create/$', login_required(views.create_event), name='create-event'),
    url(r'^(?P<event_id>[0-9]+)/decrypt/$', login_required(views.event_trustee_decrypt), name='decrypt-event'),
    url(r'^(?P<event_id>[0-9]+)/prepare/$', login_required(views.event_trustee_setup), name='prepare-event'),
    url(r'^(?P<event_id>[0-9]+)/encrypt/$', login_required(views.event_addec), name='enc-event'),
    url(r'^(?P<pk>[0-9]+)/launch/$', views.EventDetailLaunchView.as_view(), name='launch-event'),
    url(r'^edit/(?P<event_id>[0-9]+)/$', login_required(views.edit_event), name='edit-event'),
    url(r'^(?P<event_id>[0-9]+)/create/poll/$', login_required(views.manage_questions), name='create-poll'),
    url(r'^(?P<event_id>[0-9]+)/poll/(?P<poll_num>[0-9]+)/$', login_required(views.view_poll), name='view-poll'),
    url(r'^(?P<event_id>[0-9]+)/poll/(?P<poll_num>[0-9]+)/edit$', login_required(views.edit_poll), name='edit-poll'),
    #url(r'^(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='detail'),
    #url(r'^(?P<pk>[0-9]+)/results/$', login_required(views.ResultsView.as_view()), name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', login_required(views.vote), name='vote'),
]

allauthdemo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

import allauthdemo.views
import allauthdemo.auth.views
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='visitor/landing-index.html'), name='landing_index'),
    url(r'^about$', TemplateView.as_view(template_name='visitor/landing-about.html'), name='landing_about'),
    url(r'^terms/$', TemplateView.as_view(template_name='visitor/terms.html'), name='website_terms'),
    url(r'^contact$', TemplateView.as_view(template_name='visitor/contact.html'), name='website_contact'),

    url(r'^event/', include('allauthdemo.polls.urls', namespace="polls")),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', allauthdemo.auth.views.account_profile, name='account_profile'),

    url(r'^member/$', allauthdemo.views.member_index, name='user_home'),
    url(r'^member/events$', allauthdemo.views.MemberEvents.as_view(), name='account_events'),
    url(r'^member/action$', allauthdemo.views.member_action, name='user_action'),

    url(r'^admin/', include(admin.site.urls))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

allauthdemo/demo/models.py
from django.db import models

# Create your models here.

allauthdemo/polls/models.py
from __future__ import unicode_literals

from django.db import models

from django import forms

# Create your models here.

import datetime

from django.utils import timezone

from allauthdemo.auth.models import DemoUser

class EmailUser(models.Model):
    email = models.CharField(max_length=80, unique=True)

class Event(models.Model):
    users_organisers = models.ManyToManyField(DemoUser, blank=True, related_name="organisers")
    users_trustees = models.ManyToManyField(EmailUser, blank=True, related_name="trustees")
    voters = models.ManyToManyField(EmailUser, blank=True, related_name="voters")
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    prepared = models.BooleanField(default=False)
    public_key = models.CharField(null=True, blank=False, max_length=1024)
    title = models.CharField(max_length=1024)
    EID = models.CharField(max_length=512, blank=True)
    creator = models.CharField(max_length=256, blank=True)
    c_email = models.CharField(max_length=512, blank=True)
    trustees = models.CharField(max_length=4096)

class TrusteeKey(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="trustee_keys")
    user = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="trustee_keys")
    key = models.CharField(max_length=1024, unique=True) # ideally composite key here, but django doesn't really support yet

class AccessKey(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="keys")
    user = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="keys")
    key = models.CharField(max_length=1024, unique=True) # ideally composite key here, but django doesn't really support yet

    #total = models.IntegerField(blank=True, null=True, default=0)

    def has_started(self):
        return timezone.now() >= self.start

    def has_ended(self):
        return timezone.now() >= self.end

    def __unicode__(self):
        return self.title

class Poll(models.Model):
    question_text = models.CharField(max_length=200)
    total_votes = models.IntegerField(default=0)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="polls")
    enc = models.CharField(max_length=4096, null=True)

    #index = models.IntegerField()

    def __str__(self):
        return self.question_text

class Decryption(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="decryptions")
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="decryptions")
    user = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="decryptions")
    text = models.CharField(max_length=1024)

class Ballot(models.Model):
    voter = models.ForeignKey(EmailUser, on_delete=models.CASCADE, related_name="ballots")
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="ballots")
    cipher_text = models.CharField(max_length=4096)
    cast = models.BooleanField(default=False)

class PollOption(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="options")
    #index = models.IntegerField()

class Organiser(models.Model):
    index = models.IntegerField(default=0)
    email = models.CharField(max_length=100, blank=False, null=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

'''
class Organiser(models.Model):
    user = models.ForeignKey(DemoUser, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

class Trustee(models.Model):
    user = models.ForeignKey(DemoUser, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    '''
#class EventOrganisers():
    #event = models.ForeignKey(Event, on_delete=models.CASCADE)

allauthdemo/polls/polls/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

import datetime

from django.utils import timezone

class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')

  def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

  was_published_recently.admin_order_field = 'pub_date'
  was_published_recently.boolean = True
  was_published_recently.short_description = 'Published recently?'

  def __str__(self):
    return self.question_text

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)

  def __str__(self):
    return self.choice_text

allauthdemo/demo/views.py
from django.shortcuts import render

# Create your views here.

allauthdemo/polls/polls/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404, render

from django.utils import timezone

from .models import Question, Choice

from django.views import generic


""" from allauthdemo.auth.forms import RegistrationForm

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegistrationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RegistrationForm()

    return render(request, 'polls/index.html', {'form': form}) """


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
# ...
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

allauthdemo/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from allauthdemo.polls.models import Event
from django.shortcuts import get_object_or_404, render, render_to_response

@login_required
def member_index(request):
    return render_to_response("member/member-index.html", RequestContext(request))


#def member_events(request):
    #self.publisher = get_object_or_404(Publisher, name=self.args[0])
    #return Book.objects.filter(publisher=self.publisher)
    #return render_to_response("member/member-events.html", RequestContext(request))

class MemberEvents(generic.ListView):
    model = Event
    template_name = 'member/member-events.html'

    def get_context_data(self, **kwargs):
        context = super(MemberEvents, self).get_context_data(**kwargs)
        #self.object.organisers.filter(email=self.request.user.email())
        # no check needed for anon, as url should make sure we're logged in!
        return context

    def get_queryset(self):
        #self.publisher = get_object_or_404(Publisher, name=self.args[0])
        return self.request.user.organisers.all()

@login_required
def member_action(request):
    return render_to_response("member/member-action.html", RequestContext(request))




'''

class EventListView(generic.ListView):

    model = Event

    def get_context_data(self, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)
        #context['now'] = timezone.now()
        return context

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        context['is_organiser'] = ((not self.request.user.is_anonymous()) and (self.object.users.filter(email=self.request.user.email).exists()))
        #context['now'] = timezone.now()
        return context

class PollDetailView(generic.DetailView):

    model = Poll

    def get_context_data(self, **kwargs):
        context = super(PollDetailView, self).get_context_data(**kwargs)
        #context['now'] = timezone.now()
        context['form'] = VoteForm(instance=self.object)
        context['poll_count'] = self.object.event.polls.all().count()
        return context

'''

allauthdemo/templates/bases/bootstrap-auth.html
{% extends "bases/bootstrap-minimal.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2 big-box">
    {% block inner-content %}
    {% endblock %}
    </div>
  </div>
</div><!-- container -->
{% endblock %}

allauthdemo/templates/bases/bootstrap-jquery.html
{% extends "bases/bootstrap.html" %}
{% load staticfiles %}

{% block tail_js %}
<script>
  Module = {};
  Module.memoryInitializerPrefixURL = "{% static 'js/' %}";
</script>
<script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
<!-- <script>window.jQuery || document.write('<script src="js/jquery-1.10.1.min.js"><\/script>')</script> -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script src="{% static 'js/create.js' %}" type="text/javascript"></script>
<script src="{% static 'js/encrypt.js' %}" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.js" type="text/javascript"></script>

{% block app_js %}

<script type="text/javascript">


  {% block app_js_vars %}
  {% endblock %}

  Module.memoryInitializerPrefixURL = "LOL";
  var demosEncrypt = {
    param: Module.cwrap('param', 'string', ['number']),
    keygen: Module.cwrap('keygen', 'string', ['string']),
    combpk: Module.cwrap('combpk', 'string', ['string', 'string']),
    enc: Module.cwrap('enc', 'string', ['string', 'string', 'number', 'number']),
    addec: Module.cwrap('addec', 'string', ['string', 'number']),
    dec: Module.cwrap('dec', 'string', ['string', 'string']),
    tally: Module.cwrap('tally', 'string', ['string', 'string', 'string', 'number'])
  }

  demosEncrypt.encryptAndSubmit = function() {
    var answer = $('#poll-options').val();
    var cipher = demosEncrypt.enc(param, comb_pk, answer, option_count);
    $('#id_cipher_text').val(cipher);
    $('#cipher-form').submit();
  }

  demosEncrypt.decryptCipher = function() {
    var sk = $('#secret-key').val();
    if (!sk) {
      alert("Please enter your secret key");
    }
    else {
      var inputs = $("form input[type=text]");
      inputs.each(function() {
        var decryptText = demosEncrypt.dec(sk, $(this).val());
        $(this).val(decryptText);
      })
      $('input[type=submit]').prop("disabled", false);
    }
  }

  demosEncrypt.generateKeys = function() {
    parameter = $("#event-param").val();
    var genkeys= demosEncrypt.keygen(parameter);
    pk = genkeys.substring(0, genkeys.lastIndexOf('\n'));
    sk = genkeys.slice(genkeys.lastIndexOf('\n') + 1);
    $('input#public-key').val(pk);
    $('input#secret-key').val(sk);
    var blob = new Blob([sk], {type : 'text/plain'});

    var dlBtn = $('a#download-btn');
    var url = URL.createObjectURL(blob);
    var fileName =
    $(dlBtn).attr("href", url);
    $(dlBtn).attr("download", "sk-{% block sk-file-name %}{% endblock %}".replace(/[\W]/g, "-"));
    $(dlBtn).attr("disabled", false);
  }

  demosEncrypt.downloadSecretKey = function() {
    var blob = new Blob([sk], {type : 'text/plain'});
    var dlBtn = $('a#download-btn');
    $(dlBtn).attr("disabled", true);
  }

  function getFormsetPrefix(id) {
    id = id.replace(/(?:id_)?formset_/, ""); // strip generic part
    return id.replace(/([A-Za-z0-9]+)[\w-]*/, "$1"); // return prefix
  }

  function setFormsetIndex(ele, prefix, index) {
    ele = $(ele).find("div[id^='id_formset'], input[id^='id_formset']").each(function (i, el) {
     var id = $(el).attr("id");
     id = "id_formset_" + prefix + '-' + index + id.match(/-\w+$/);
     $(el).attr("id", id);
     if ($(el).is("input")) {
       $(el).attr("name", id.replace(/^id_/, ""));
     }
   });
  }

  $('.formset').sortable({handle:".input-group-addon", items:".formset_object",
    start: function(event, ui) {
      ui.item.prevPos = ui.item.index();
      console.log(ui.item.prevPos);
    },
    update: function(event, ui) {
      ui.item.prevPos = null;
    },
    beforeStop: function(event, ui) {
      $(ui.item).css("animation", "none"); // prevents firing of entry keyframe
    }
  });
  //$('.glyphicon.glyphicon-trash').parent().hide();
  $('.formset').find
  $('.formset').on('click', '.input-group-addon', function() { // this makes the label a delete btn too :(
    var ele = $(this).closest(".formset_object");
    var prefix = $(this).closest(".formset_object").data("prefix") || getFormsetPrefix($(this).closest(".formset_object").find('input:first').attr("id"));
    var current_total = parseInt($("#id_formset_" + prefix + "-TOTAL_FORMS").val());
    if (current_total <= $("#id_formset_" + prefix + "-MIN_NUM_FORMS").val()) {
      return; // don't allow removal of last element
    }
    ele.remove();
    $("#id_formset_" + prefix + "-TOTAL_FORMS").val(current_total - 1);
    $(".formset").sortable( "refresh" );
    $(".formset").sortable( "refreshPositions" );
  });
  $('.add-another-btn').on('click',function() {
    var new_formset_item = $(this).prevAll(".formset_object:first").clone();
    var prefix = getFormsetPrefix(new_formset_item.find("input:first").attr("id"));
    var current_total = parseInt($("#id_formset_" + prefix + "-TOTAL_FORMS").val());
    if (current_total >= $("#id_formset_" + prefix + "-MAX_NUM_FORMS").val()) {
      return; // don't allow more than max forms
    }
    new_formset_item.data("prefix", prefix);
    $(this).before(new_formset_item);
    new_formset_item.find("input").val("");
    setFormsetIndex(new_formset_item, prefix, parseInt($("#id_formset_" + prefix + "-TOTAL_FORMS").val()));
    $("#id_formset_" + prefix + "-TOTAL_FORMS").val(parseInt($("#id_formset_" + prefix + "-TOTAL_FORMS").val()) +1);
    $(".formset").sortable( "refresh" );
    $(".formset").sortable( "refreshPositions" );
  });

  // rudimentary accordion error handling
  $('.has-error').closest('.panel').find('.panel-heading').addClass("error");
  $('.alert.alert-block.alert-danger').closest('.panel').find('.panel-heading').addClass("error");
</script>

{% endblock %}

{% endblock %}

allauthdemo/templates/bases/bootstrap-member.html
{% extends "bases/bootstrap-jquery.html" %}
{% load staticfiles %}
{% block nav %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-static-top navbar-shadow" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'user_home' %}">Demo Members Area</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'user_home' %}">Home</a></li>
            <li><a href="{% url 'user_action' %}">Action</a></li>
            <li><a href="{% url 'polls:index' %}">Polls</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <strong> {{ user.display_name }}</strong> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Account</li>
                <li><a href="{% url 'account_profile' %}"><i class="fa fa-cog"></i> Settings</a></li>
                <li><a href="{% url 'account_events' %}"><i class="fa fa-bell"></i> My Events</a></li>
                <li><a href="{% url 'account_email' %}"><i class="fa fa-envelope"></i> Email Addresses</a></li>
                <li><a href="{% url 'socialaccount_connections' %}"><i class="fa fa-facebook"></i> Social Networks</a></li>
                <li><a href="{% url 'account_change_password' %}"><i class="fa fa-lock"></i> Change Password</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> Sign Out</a></li>
              </ul>
            </li>
            <li>{% if user.profile.avatar_url %}<img alt="" style="width:50px; height:50px" src="{{user.profile.avatar_url}}">{% endif %}</li>
          </ul>
        </div>
      </div>
    </div>

{% endblock %}

allauthdemo/templates/bases/bootstrap-visitor.html
{% extends "bases/bootstrap-jquery.html" %}
{% load staticfiles %}

{% block nav %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-static-top navbar-shadow" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src='{% static "img/demos2-banner.png" %}' style="height:100%" title="demos2"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'landing_index' %}">Welcome</a></li>
            <li><a href="{% url 'landing_about' %}">About</a></li>
            <li><a href="{% url 'polls:index' %}">Polls</a></li>
            <li><a href="{% url 'account_signup' %}"><strong>Join</strong></a></li>
            <li><a href="{% url 'account_login' %}"><strong>Log In</strong></a></li>
          </ul>
        </div>
      </div>
    </div>

{% endblock %}

allauthdemo/templates/bases/bootstrap-with-nav.html
{% extends "bases/bootstrap-jquery.html" %}
{% load staticfiles %}

{% block nav %}
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-static-top navbar-shadow" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src='{% static "img/demos2-banner.png" %}' style="height:100%" title="demos2"></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'landing_index' %}">Welcome</a></li>
            <li><a href="{% url 'landing_about' %}">About</a></li>
            <li><a href="{% url 'polls:index' %}">Polls</a></li>
            {% if user.is_authenticated %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <strong> {{ user.display_name }}</strong> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="dropdown-header">Account</li>
                  <li><a href="{% url 'account_profile' %}"><i class="fa fa-cog"></i> Settings</a></li>
                  <li><a href="{% url 'account_events' %}"><i class="fa fa-bell"></i> My Events</a></li>
                  <li><a href="{% url 'account_email' %}"><i class="fa fa-envelope"></i> Email Addresses</a></li>
                  <li><a href="{% url 'socialaccount_connections' %}"><i class="fa fa-facebook"></i> Social Networks</a></li>
                  <li><a href="{% url 'account_change_password' %}"><i class="fa fa-lock"></i> Change Password</a></li>
                  <li class="divider"></li>
                  <li><a href="{% url 'account_logout' %}"><i class="fa fa-sign-out"></i> Sign Out</a></li>
                </ul>
              </li>
              <li>{% if user.profile.avatar_url %}<img alt="" style="width:50px; height:50px" src="{{user.profile.avatar_url}}">{% endif %}</li>
            {% else %}
              <li><a href="{% url 'account_signup' %}"><strong>Join</strong></a></li>
              <li><a href="{% url 'account_login' %}"><strong>Log In</strong></a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

{% endblock %}